apiVersion: batch/v1
kind: Job
metadata:
  name: read-db-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: read-db
      labels:
        app: read-db
    spec:
      containers:
        - name: read-db
          image: homesrh/read_db:4.0
      restartPolicy: Never
